### ISSUE TITLE
Using navigationStart as a measure's startTime

### ISSUE THREAD

**Issue by paulirish** [w3c/user-timing#44] opened 2018-08-16 20:50 UTC
Related: #22

What's the reliable way to get a measure that starts at navigationStart and ends with a provided mark time?

I've been using the following successfully:

```js
// ...
performance.mark('initComplete');
performance.measure('navStartToInitComplete', undefined, 'initComplete');
```

... successfully, _until_ Chrome 68, when it started throwing a DOMException. :(

But... AFAICT, the L2 spec allows this:
* [`startMark` is `optional`](https://w3c.github.io/user-timing/#extensions-performance-interface)
* [`If startMark is omitted, let start time be 0.`](https://w3c.github.io/user-timing/#measure-method)

This case (omitted startMark, provided endMark) seems underspecced, and turns out, it's [not](https://github.com/web-platform-tests/wpt/blob/d617cdbf1278785ebcfd949be18231b7fc0eebed/user-timing/measure.html#L28-L69) [tested](https://github.com/web-platform-tests/wpt/blob/d617cdbf1278785ebcfd949be18231b7fc0eebed/user-timing/measure.html#L110-L156) either. 

From talking briefly to Philip it sounds like L2 is probably not going to resolve this, but something to keep in mind for L3.

In the meantime, **should I file a browser bug against Chrome for this?** (The exception is `Failed to execute 'measure' on 'Performance': The mark 'null' does not exist.`)

------

Also: I know the L1 spec provided the hack of using 'navigationStart' as a string, and that the WG is interested in removing that approach. So I'm hesitant to use it now since it may start throwing in the future.

If L3 allows passing a `PerformanceEntry` as startTime, then I could pass the `performance.getEntriesByType("navigation")[0]`, right?

**Comment by yoavweiss** [comment] 2018-08-17 15:37
> ... successfully, until Chrome 68, when it started throwing a DOMException. :(

If I were a betting man, I'd put my money on https://chromium-review.googlesource.com/c/chromium/src/+/871507 :/

[`start`](https://cs.chromium.org/chromium/src/third_party/blink/renderer/core/timing/performance_user_timing.cc?sq=package:chromium&dr&g=0&l=171) was modified from String to StringOrDouble, and I'm not sure where `undefined` falls there.

/cc @npm1 @tdresser 


> But... AFAICT, the L2 spec allows this:
> 
> startMark is optional
> If startMark is omitted, let start time be 0.

I agree with your reading of the current processing model. Firefox also seems to agree.

> This case (omitted startMark, provided endMark) seems underspecced

I think it's well-defined, and the start time should've been 0 here.

> and turns out, it's not tested either.

That's probably the root-cause here, and the reason this regression wasn't caught


> In the meantime, should I file a browser bug against Chrome for this?

Yes, and please CC me on it.

In the meantime, I think we need to keep this issue open until tests are added to make sure this doesn't regress again.

**Comment by tdresser** [comment] 2018-08-17 16:04
L3 will enable this. Details currently [here](https://docs.google.com/document/d/1hltt8z9C4PaI5Qu1YMIp1wOGdbJPJPoJwBarEeCY6xQ/edit#heading=h.ejti6qhmjv0b).

Thanks for the bug report. Please cc npm@ and maxlg@ as well.

**Comment by npm1** [comment] 2018-08-17 16:11
In https://chromium-review.googlesource.com/c/chromium/src/+/871507 the start is changed from null to the string 'null', so when we measure we try to find a mark with that name. I don't think that CL was supposed to change L2 behavior? Probably accidentally introduced the bug.

**Comment by maxlgu** [comment] 2018-08-17 19:36
Thanks for finding this. That's very likely be the fault of my CL. Yes the L3 is not supposed to change the L2 behavior. I used a lot of hacks to make the disabled L3 API consistent with L2. But this use case is a miss.

**Comment by maxlgu** [comment] 2018-08-17 20:04
I remember that there is some subtlety in the L2 API. Passing null is different from passing undefined. When passing null, the API treats it as string "null", when passing undefined, it is an empty argument.

Safari and Chrome (the original L2) both agree this behavior. Have we specified this behavior?

**Comment by maxlgu** [comment] 2018-08-17 20:14
> start was modified from String to StringOrDouble, and I'm not sure where undefined falls there.

Right. Is there a way to tell null, undefined apart while using StringOrDouble? Or do we just want to treat both null and undefined as undefined? It seems strange to me that null become 'null' after passing it to API.

Do we want to change this behavior?

**Comment by npm1** [comment] 2018-08-17 20:15
My reading of the spec is: currently it receives a 'optional DOMString startMark', which is not a nullable type. Thus passing in null is basically wrong so Javascript casts it to a string, the string "null" maybe? I don't know. Whereas passing undefined means that the variable is not defined, which is interpreted as the variable being omitted (which is accepted because it's marked as optional). This would explain why null behaves differently from undefined and is consistent with the spec.

**Comment by maxlgu** [comment] 2018-08-21 16:12
It's weird to me that null was treated as "null" in M67 and Safari. Intuitively undefined and null should be treated as the same input.
I've submitted a fix by treating both undefined and null as undefined, for the parameter start and end. Although back compatibility is broken for the edge case of passing null to start/end, I guess this use case is rare enough.
The reason why we don't make a full fix is because after introducing User Timing L3, the API has become complicated enough that it's technically hard to distinguish between null and undefined for the start parameter. 
Given that the original behavior was strange, I think it worth discussion about whether we want to keep the original behavior or treat null and undefined as no difference.

**Comment by yoavweiss** [comment] 2018-09-19 07:57
I believe test coverage for this have landed: https://github.com/web-platform-tests/wpt/pull/12556
Closing, but @npm1 & @maxlgu please let me know if you think this should requires more test coverage.

**Closed by yoavweiss** 2018-09-19 07:57 UTC
Labels: test:missing-coverage

**Comment by maxlgu** [comment] 2018-09-24 14:36
Sure. I don't think we need more test coverage for now.
